name: Slack Testing

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  slack-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Slack Test Step
        run: echo "This is a test step for Slack integration."

      - name: Reusable workflow within a job step testing
        uses: ./.github/workflows/notify-slack.yml
        with:
          message: "Testing inside job step"
        secrets: inherit
