name: Slack Testing

on:
  push:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  notify-slack:
    uses: ./.github/workflows/notify-slack.yml
    with:
      message: "Testing"
    secrets:
      PR_OBSERVER_SLACK_WEBHOOK_URL: ${{ secrets.PR_OBSERVER_SLACK_WEBHOOK_URL }}
