name: Wait for Approval

on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  notify-slack:
    uses: ./.github/workflows/notify-slack.yml
    with:
      message: "‚è≥ A deployment to production is awaiting approval"
    secrets:
      PR_OBSERVER_SLACK_WEBHOOK_URL: ${{ secrets.PR_OBSERVER_SLACK_WEBHOOK_URL }}

  wait-for-approval:
    runs-on: ubuntu-latest
    environment: approval
    steps:
      - name: Wait for approval
        run: echo "Waiting for approval to proceed to the next stage"
