name: Wait for Approval

on:
  worflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  wait-for-approval:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Wait for approval
        run: echo "Waiting for approval to proceed to the next stage"


